version: '3.8'

services:
  app:
    build: .
    container_name: fastapi_app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./localDB.sqlite
    volumes:
      - .:/app

volumes:
  sqlite_data:
